CREATE DATABASE tp4;
USE tp4;
CREATE TABLE PRECIOS_ESPECTACULOS (
    COD_PRECIO INT NOT NULL AUTO_INCREMENT,
    COD_COMPLEJO INT NOT NULL,
    NRO_SALA INT NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (COD_PRECIO) 
);
CREATE TABLE COMPLEJOS (
    COD_COMPLEJO INT NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    DIRECCION VARCHAR(30) NOT NULL,
    CIUDAD VARCHAR(20) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    HORARIO_APERTURA VARCHAR(5) NOT NULL,
    HORARIO_CIERRE VARCHAR(5) NOT NULL,
    PRIMARY KEY (COD_COMPLEJO) 
);
CREATE TABLE SALAS (
    NRO_SALA INT NOT NULL,
    TIPO VARCHAR(15) NOT NULL,
    CAPACIDAD INT NOT NULL,
    COD_COMPLEJO INT NOT NULL,
    COD_PELICULA INT NOT NULL,
    PRIMARY KEY (NRO_SALA) 
);
CREATE TABLE ASIENTOS (
    ID_ASIENTO INT NOT NULL AUTO_INCREMENT,
    FILA INT NOT NULL,
    NUMERO INT NOT NULL,
    NRO_SALA INT NOT NULL,
    PRIMARY KEY (ID_ASIENTO)
);
CREATE TABLE PELICULA (
    COD_PELICULA INT NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    CALIFICACION VARCHAR(8) NOT NULL,
    PRIMARY KEY (COD_PELICULA) 
);
CREATE TABLE ENTRADAS (
    ID_ENTRADA INT NOT NULL AUTO_INCREMENT,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    TIPO VARCHAR(30) NOT NULL,
    NRO_SALA INT NOT NULL,
    ID_ASIENTO INT NOT NULL,
    PRIMARY KEY (ID_ENTRADA) 
);
CREATE TABLE ESPECTADORES (
    ID_ESPECTADOR INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(30) NOT NULL,
    DIRECCION VARCHAR(20) NOT NULL,
    TELEFONO VARCHAR(12) NOT NULL,
    CIUDAD VARCHAR(30) NOT NULL,
    NTARJETA VARCHAR(20) NOT NULL,
    ID_ENTRADA INT NOT NULL,
    PRIMARY KEY (ID_ESPECTADOR)
);

ALTER TABLE PRECIOS_ESPECTACULOS
    ADD CONSTRAINT FK_PRECIOS_ESPECTACULOS_SALAS FOREIGN KEY (NRO_SALA) REFERENCES SALAS(NRO_SALA),
    ADD CONSTRAINT FK_PRECIOS_ESPECTACULOS_COMPLEJOS FOREIGN KEY (COD_COMPLEJO) REFERENCES COMPLEJOS(COD_COMPLEJO);

ALTER TABLE SALAS
    ADD CONSTRAINT FK_SALAS_COMPLEJOS FOREIGN KEY (COD_COMPLEJO) REFERENCES COMPLEJOS(COD_COMPLEJO),
    ADD CONSTRAINT FK_SALAS_PELICULA FOREIGN KEY (COD_PELICULA) REFERENCES PELICULA(COD_PELICULA);

ALTER TABLE ASIENTOS
    ADD CONSTRAINT FK_ASIENTOS_SALAS FOREIGN KEY (NRO_SALA) REFERENCES SALAS(NRO_SALA);

ALTER TABLE ENTRADAS
    ADD CONSTRAINT FK_ENTRADAS_SALAS FOREIGN KEY (NRO_SALA) REFERENCES SALAS(NRO_SALA),
    ADD CONSTRAINT FK_ENTRADAS_ASIENTOS FOREIGN KEY (ID_ASIENTO) REFERENCES ASIENTOS(ID_ASIENTO);

ALTER TABLE ESPECTADORES
    ADD CONSTRAINT FK_ESPECTADORES_ENTRADAS FOREIGN KEY (ID_ENTRADA) REFERENCES ENTRADAS(ID_ENTRADA);

ALTER TABLE pelicula
    CHANGE `CALIFICACION` `CALIFICACION` ENUM('G', 'PG', 'PG-13', 'R', 'NC-17') NOT NULL;

-- AGREGAR EDAD Y RESTRICCION DE EDAD A LA TABLA ESPECTADORES
ALTER TABLE ESPECTADORES
    ADD COLUMN EDAD INT NOT NULL,
    ADD CONSTRAINT CK_EDAD CHECK (EDAD >= 18);

-- PELICULAS
INSERT INTO PELICULA (COD_PELICULA, NOMBRE, FECHA, HORA, CALIFICACION) VALUES (1, 'El Padrino', '1972-03-24', '14:00:00', 'R');
INSERT INTO PELICULA (COD_PELICULA, NOMBRE, FECHA, HORA, CALIFICACION) VALUES (2, 'El Padrino II', '1974-12-20', '14:00:00', 'R');
INSERT INTO PELICULA (COD_PELICULA, NOMBRE, FECHA, HORA, CALIFICACION) VALUES (3, 'El Padrino III', '1990-12-25', '14:00:00', 'R');
INSERT INTO PELICULA (COD_PELICULA, NOMBRE, FECHA, HORA, CALIFICACION) VALUES (4, 'El Señor de los Anillos I', '2001-12-19', '14:00:00', 'PG-13');
INSERT INTO PELICULA (COD_PELICULA, NOMBRE, FECHA, HORA, CALIFICACION) VALUES (5, 'El Señor de los Anillos II', '2002-12-18', '14:00:00', 'PG-13');

-- Complejos
INSERT INTO COMPLEJOS (COD_COMPLEJO, NOMBRE, DIRECCION, CIUDAD, TELEFONO, HORARIO_APERTURA, HORARIO_CIERRE) VALUES (1, 'Cine Victor', 'Calle 123', 'CABA', '1234567890', '10:00', '22:00');
INSERT INTO COMPLEJOS (COD_COMPLEJO, NOMBRE, DIRECCION, CIUDAD, TELEFONO, HORARIO_APERTURA, HORARIO_CIERRE) VALUES (2, 'Cine Victor II', 'Calle 456', 'CABA', '0987654321', '10:00', '22:00');

-- Salas
INSERT INTO SALAS (NRO_SALA, TIPO, CAPACIDAD, COD_COMPLEJO, COD_PELICULA) VALUES (1, '2D', 100, 1, 1);
INSERT INTO SALAS (NRO_SALA, TIPO, CAPACIDAD, COD_COMPLEJO, COD_PELICULA) VALUES (2, '2D', 100, 1, 2);

-- Asientos
INSERT INTO ASIENTOS (FILA, NUMERO, NRO_SALA) VALUES (1, 1, 1);
INSERT INTO ASIENTOS (FILA, NUMERO, NRO_SALA) VALUES (1, 2, 1);
INSERT INTO ASIENTOS (FILA, NUMERO, NRO_SALA) VALUES (1, 3, 1);

-- Entradas
INSERT INTO ENTRADAS (FECHA, HORA, NOMBRE, TIPO, NRO_SALA, ID_ASIENTO) VALUES ('2021-06-01', '14:00:00', 'El Padrino', '2D', 1, 1);
INSERT INTO ENTRADAS (FECHA, HORA, NOMBRE, TIPO, NRO_SALA, ID_ASIENTO) VALUES ('2021-06-01', '14:00:00', 'El Padrino II', '2D', 1, 2);

-- Precios
INSERT INTO PRECIOS_ESPECTACULOS (COD_COMPLEJO, NRO_SALA, PRECIO) VALUES (1, 1, 500);
INSERT INTO PRECIOS_ESPECTACULOS (COD_COMPLEJO, NRO_SALA, PRECIO) VALUES (1, 2, 500);

-- Espectadores
INSERT INTO ESPECTADORES (NOMBRE, DIRECCION, TELEFONO, CIUDAD, NTARJETA, ID_ENTRADA, EDAD) VALUES ('Maria Lopez', 'Calle 456', '0987654321', 'CABA', '6543210987654321', 2, 18);
INSERT INTO ESPECTADORES (NOMBRE, DIRECCION, TELEFONO, CIUDAD, NTARJETA, ID_ENTRADA, EDAD) VALUES ('Juan Perez', 'Calle 123', '1234567890', 'CABA', '1234567890123456', 3, 19);
