CREATE TABLE IF NOT EXISTS `TP3EyBDD`.`LOCALIDAD` (
    `COD_LOCALIDAD` INT PRIMARY KEY,
    `NOMBRE` VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS `TP3EyBDD`.`PUB` (
    `COD_PUB` INT PRIMARY KEY NOT NULL,
    `NOMBRE` VARCHAR(50) NOT NULL,
    `LICENCIA_FISCAL` CHAR(20) NULL,
    `DOMICILIO` VARCHAR(100) NULL,
    `FECHA_APERTURA` DATE NULL,
    `HORARIO` ENUM('HOR1', 'HOR2', 'HOR3') NULL,
    `COD_LOCALIDAD` INT NULL,
    CONSTRAINT `fk_pub_localidad`
    FOREIGN KEY (`COD_LOCALIDAD`) 
    REFERENCES `TP3EyBDD`.`LOCALIDAD`(`COD_LOCALIDAD`)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `TP3EyBDD`.`TITULAR` (
	`DNI_TITULAR` CHAR(11) PRIMARY KEY,
    `NOMBRE` VARCHAR(50) NOT NULL,
    `DOMICILIO` VARCHAR(100),
    `COD_PUB` INT,
    CONSTRAINT `fk_titular_pub`
    FOREIGN KEY (`COD_PUB`) 
    REFERENCES `TP3EyBDD`.`PUB`(`COD_PUB`)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `TP3EyBDD`.`EMPLEADO` (
    `DNI_EMPLEADO` CHAR(11) PRIMARY KEY,
    `NOMBRE` VARCHAR(50) NOT NULL,
    `DOMICILIO` VARCHAR(100),
	`COD_PUB` INT,
    CONSTRAINT `fk_empleado_pub`
    FOREIGN KEY (`COD_PUB`)
    REFERENCES `TP3EyBDD`.`PUB`(`COD_PUB`)
);

CREATE TABLE IF NOT EXISTS `TP3EyBDD`.`EXISTENCIAS` (
    `COD_ARTICULO` INT PRIMARY KEY,
    `NOMBRE` VARCHAR(50) NOT NULL,
    `CANTIDAD` INT,
    `PRECIO` DECIMAL(10,2) CHECK (PRECIO > 0),
    `COD_PUB` INT,
    CONSTRAINT `fk_existencias_pub`
    FOREIGN KEY (`COD_PUB`)
    REFERENCES `TP3EyBDD`.`PUB`(`COD_PUB`)
);

CREATE TABLE IF NOT EXISTS `TP3EyBDD`.`PUB_EMPLEADO` (
    `COD_PUB` INT,
    `DNI_EMPLEADO` CHAR(11),
    `FUNCION` ENUM('CAMARERO', 'SEGURIDAD', 'LIMPIEZA'),
    CONSTRAINT `fk_pub_empleado_pub`
    FOREIGN KEY (`COD_PUB`) REFERENCES `TP3EyBDD`.`PUB`(`COD_PUB`),
    CONSTRAINT `fk_pub_empleado_empleado`
    FOREIGN KEY (`DNI_EMPLEADO`) REFERENCES `TP3EyBDD`.`EMPLEADO`(`DNI_EMPLEADO`)
);